### ISSUE TITLE
[OsuRTDataProviderPlugin]System.NullReferenceException: Object reference not set to an instance of an object.    at OsuRTDataProvider.Listen.OsuListenerManager.ListenLoopUpdate()

### ISSUE THREAD

**Issue by kapiwulon** [OsuSync/OsuRTDataProvider#27]
[19:28:29] [OsuRTDataProviderPlugin]osu!version compatible condition: 20200111.3 < 20190816 ?
[19:28:29] [OsuRTDataProviderPlugin]Beatmap Base Address (0):0x00000000
[19:28:29] [OsuRTDataProviderPlugin]Beatmap Base Address (1):0x00000000
[19:28:29] [OsuRTDataProviderPlugin][ID:0]Init BeatmapFinder Failed! Retry after 3 seconds
[19:28:29] [OsuRTDataProviderPlugin]System.NullReferenceException: Object reference not set to an instance of an object.
   at OsuRTDataProvider.Listen.OsuListenerManager.ListenLoopUpdate()

**Comment by KedamaOvO** [comment]
https://github.com/OsuSync/OsuRTDataProvider/releases/tag/v1.5.12
